# Generated by Django 4.0.4 on 2022-05-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('field_name', models.CharField(max_length=200)),
                ('field_rename', models.CharField(max_length=200)),
                ('map_name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
